name: test
on: [push, pull_request]

jobs:
     test:
         runs-on: ubuntu-latest
         steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-python@v2
           with:
               python-version: '3.9'
         - name: Install dependencies
           run: python -m pip install mock==4.0.3 pytest==6.2.3 isort==3.8.0 black==20.8b1 pyflakes==2.3.1
         - name: Run tests
           run: python -m pytest
         - name: Check imports are sorted
           run: isort --check-only cleverdiff
         - name: Check code formatting
           run: black --check --diff --color cleverdiff
         - name: Check for flaky code
           run: pyflakes .

